version: '3.8'

services:
  # Service pour la base de données PostgreSQL
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-default_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-default_password}
      POSTGRES_DB: ${POSTGRES_DB:-default_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Service pour Adminer (interface web pour gérer PostgreSQL)
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "${ADMINER_PORT:-8080}:${ADMINER_PORT:-8080}"
    networks:
      - app-network

  # Service pour le backend FastAPI
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "${BACKEND_PORT:-8081}:8000"
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://default_user:default_password@db:5432/default_db}
    depends_on:
      - db
    networks:
      - app-network

  # Service pour le frontend Vue.js
  frontend:
    build: ./frontend
    container_name: vue-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:5173"
    working_dir: /app
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      VUE_APP_API_URL: ${VUE_APP_API_URL:-http://localhost:8081}

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
